Homework 2.v1
badyornyi/itlabs_selruby pull request #2
Opened 2016-12-20 21:54 UTC by badyornyi

All tasks for Homework 2 (Main Data and Collection Classes) are finished

2016-12-22 14:21 UTC, d-konovalov requested changes

2016-12-22 14:21 UTC, d-konovalov commented on main_data_classes.rb
> +#6. There is an array of integers (ary). Puts the index of the last element where ary[0]<ary[i]<ary[-1]
And what if your array will have integers in different order?
Please discover other cases

2016-12-22 14:21 UTC, d-konovalov commented on main_data_classes.rb
> +#8. There is a hash where keys and values are strings. Modify it: all keys should be symbols and all values should be integers. If you couldn't modify some value set it to nil
'Modify' means that you should transform your keys-strings to symbols but not deleting them completely

2016-12-24 14:02 UTC, badyornyi commented on main_data_classes.rb
> +#6. There is an array of integers (ary). Puts the index of the last element where ary[0]<ary[i]<ary[-1]
Requested changes for Task#6 are done

2016-12-24 14:07 UTC, badyornyi commented on main_data_classes.rb
> +#8. There is a hash where keys and values are strings. Modify it: all keys should be symbols and all values should be integers. If you couldn't modify some value set it to nil
Requested changes for Task#8 are done.
But I don't sure about its correctness

2016-12-29 13:23 UTC, d-konovalov requested changes

2016-12-29 13:23 UTC, d-konovalov commented on main_data_classes.rb
> +#6. There is an array of integers (ary). Puts the index of the last element where ary[0]<ary[i]<ary[-1]
what if the array would look like this:
```[3,1,5,7,8,0,2,9]```
I would expect index of element 8 as an answer

2016-12-29 13:23 UTC, d-konovalov commented on main_data_classes.rb
> +#8. There is a hash where keys and values are strings. Modify it: all keys should be symbols and all values should be integers. If you couldn't modify some value set it to nil
if you'll call
``` 'my_string'.to_sym```
you get ``` :my_string``` instead

2017-01-10 10:21 UTC, merged