Hw6 exceptions
badyornyi/itlabs_selruby pull request #7
Opened 2017-04-10 19:13 UTC by badyornyi

Added test for rescuing exception

2017-04-10 19:35 UTC, d-konovalov requested changes

2017-04-10 19:35 UTC, d-konovalov commented on main_project/our_module.rb
> +  def open_project(project_name)
too big method
split it into logical parts please

2017-04-11 09:23 UTC, d-konovalov commented on main_project/our_module.rb
> +  def is_project_in_list?(project_name, projects)
could you please explain what does this method should do, please?

2017-04-11 11:01 UTC, badyornyi commented on main_project/our_module.rb
> +  def is_project_in_list?(project_name, projects)
"is_project_in_list?" method looks for project name (project that has to be opened) in the all existing projects names list.
If there is no such project in the list - it sets @exist to false

2017-04-11 13:02 UTC, d-konovalov requested changes

2017-04-11 13:02 UTC, d-konovalov commented on main_project/our_module.rb
> +  def is_project_in_list?(project_name, projects)
I would suggest you to change it

1. get all projects titles
2. verify that this array includes project name you're looking for

2017-04-12 08:21 UTC, d-konovalov commented on main_project/our_module.rb
> +    @driver.find_elements(:css => '.project.root.leaf').map! do |project_element|
here is some syntax sugar:
map block in this case can be replaced with this:


```ruby
ary.map(&:text)
```

2017-04-12 08:21 UTC, d-konovalov commented on main_project/our_module.rb
> +  def is_project_in_list?(project_name)
here is a more suitable method for such cases:


```ruby
ary.include?(element)
```

2017-04-12 09:24 UTC, d-konovalov approved these changes

2017-04-12 09:24 UTC, merged